In [1]:
import pandas as pd
import json
import os

In [3]:
routes=pd.read_json('routes.json')
routes.head()

                   Airlines source destination
0           IndiGo-American    CCU         DEL
1           IndiGo-American    DEL         JFK
2           IndiGo-American    JFK         ORD
3  American-British Airways    HYD         LHR
4  American-British Airways    LHR         JFK

In [4]:
routes.shape

(149, 3)

In [5]:
#For a given airline and destination find source
dest=pd.read_json('air_dest.json')
dest

                    Airlines destination
0            IndiGo-American         ORD
1  Air India-British Airways         CPT
2             Vistara-United         SEA
3   American-British Airways         EZE

In [6]:
rgroup=routes.groupby('Airlines')

In [7]:
type(rgroup)

pandas.core.groupby.generic.DataFrameGroupBy

In [8]:
def get_source(g,dest):
    x=g[g['destination']==dest]
    if x.empty:
        return dest
    src=x['source'].iloc[0]
    return get_source(g,src)

In [9]:
with open('mapping.json','r') as f:
    tags=json.load(f)

In [10]:
%time
rgroup=routes.groupby('Airlines')
source=[]
for i,r in dest.iterrows():
    g=rgroup.get_group(r['Airlines'])
    src=get_source(g,r['destination'])
    #print({'Airlines':r['Airlines'],'Source':src,'Destination':r['destination']})
    source.append({'Airlines':r['Airlines'],'Destination':(r['destination'],tags[r['destination']]),'Source':(src,tags[src])})

CPU times: total: 0 ns
Wall time: 0 ns

In [11]:
source=pd.DataFrame(source)
source

,Airlines,Destination,Source
0,IndiGo-American,"(ORD, O'Hare International Airport)","(CCU, Netaji Subhas Chandra Bose International..."
1,Air India-British Airways,"(CPT, Cape Town International Airport)","(GAU, Lokpriya Gopinath Bordoloi International..."
2,Vistara-United,"(SEA, Seattle-Tacoma International Airport)","(COK, Cochin International Airport)"
3,American-British Airways,"(EZE, Ministro Pistarini International Airport...","(HYD, Rajiv Gandhi International Airport)"